global:
  nfsServer: 192.168.10.143
  storageClass: nfs-client

backend:
  image: excelazmin/mern-blog-server:latest
  replicaCount: 2
  dbUrl: "mongodb://root:example@mongodb:27017/mydb?authSource=admin"
  servicePort: 5001
  imageStorageSize: 1Gi

frontend:
  image: excelazmin/mern-blog-client:latest
  replicaCount: 2
  servicePort: 3000
  containerPort: 80

mongodb:
  image: mongo:5.0
  replicaCount: 1
  servicePort: 27017
  storageSize: 20Gi
  rootUsername: root
  rootPassword: example

ingress:
  enabled: true
  backendHost: blog-api.myapps.com
  frontendHost: blog.myapps.com