apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: { { .Values.backend.replicaCount } }
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: { { .Values.backend.image } }
          ports:
            - containerPort: { { .Values.backend.servicePort } }
          volumeMounts:
            - name: images-storage
              mountPath: /app
          env:
            - name: DB_URL
              value: { { .Values.backend.dbUrl | quote } }
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password

      volumes:
        - name: images-storage
          persistentVolumeClaim:
            claimName: backend-images-pvc
