apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-images-pvc
spec:
  storageClassName: { { .Values.global.storageClass } }
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: { { .Values.backend.imageStorageSize } }
